### ISSUE TITLE
Codegen?

### ISSUE THREAD

**Issue by dwhitney** [hoodunit/purescript-payload#1]
Hi this is a cool project! Have you got any tooling somewhere to codegen types from a json file? If not I could perhaps contribute some tooling since I need it anyway

**Comment by hoodunit** [comment]
Hey, thanks. This project does not actually do any code generation - it's all derivation at compile time. But in purescript-kubernetes I generate PureScript code from the Kubernetes API JSON schema definitions. You could take a look in https://github.com/hoodunit/purescript-kubernetes/tree/master/src/Kubernetes/Generation and see if any of that is useful. There's a command `npm run build-generation` to run the generation script. The generated code is committed to source in https://github.com/hoodunit/purescript-kubernetes/tree/master/src/Kubernetes/Api. The code might need some updating for latest PS, but take a look and ping me on e.g. FP Slack if there are questions. I've been thinking of pulling some of that out to a more JSON schema -specific library but haven't gotten around to it.
