### ISSUE TITLE
Post with empty body

### ISSUE THREAD

**Issue by jim108dev** [hoodunit/purescript-payload#19]
Hi! `DecodeBody` is mandatory for a `POST` request. Can you make it optional?
The RealWorld API Spec has a POST with empty body at *Follow user*.
Thanks

**Comment by hoodunit** [comment]
Yeah it looks like the HTTP spec declares it optional as well. I've made it optional here https://github.com/hoodunit/purescript-payload/commit/49fd386b80e5236eba007b2aac9a526eea05658a and unless there are issues with that I'll close this when I get around to making a release.

**Comment by jim108dev** [comment]
ok, thank you.

**Comment by hoodunit** [comment]
Should be good to go in [v0.4.0](https://github.com/hoodunit/purescript-payload/releases/tag/v0.4.0) now.
