### ISSUE TITLE
Release for 0.14.X

### ISSUE THREAD

**Issue by Zelenya7** [hoodunit/purescript-payload#24]
Could you please make a release? :pray: 
The master looks pretty good, it would be nice to have a tagged version, so it could also be added back to package set.

**Comment by hoodunit** [comment]
Makes sense to me. I pushed a release to Bower now and I'll get it into a package set when I get a moment.

**Comment by Zelenya7** [comment]
Thank you for the release, I've created a PR to package set 
https://github.com/purescript/package-sets/pull/964
